package:
  name: geoscripts
  version: 0.0.2

source:
  git_url: "https://github.com/dyvasey/geoscripts"
  git_rev: "develop-package"

requirements:

  host:
    - python
    - setuptools
    - numpy
    - geos
    - proj
  
  run:
    - python
    - geos
    - proj

about:
  home: "https://github.com/dyvasey/geoscripts"