package:
  name: geoscripts
  version: 0.2.0

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - pip
    - geos
    - proj
    - numpy>=1.10
    - cython
  
  run:
    - python
    - geos
    - proj
    - numpy>=1.10
    - pandas=1.5.1
    - matplotlib
    - seaborn
    - scipy
    - shapely
    - cartopy
    - statsmodels
    - geopandas
    - mpltern
    - pyrolite

test:
  imports:
    - geoscripts
    - geoscripts.dz

about:
  home: "https://github.com/dyvasey/geoscripts"