name: geoscripts
channels:
  - conda-forge
  - defaults
dependencies:
    - python=3.10
    - numpy>=1.10
    - pandas
    - matplotlib
    - seaborn
    - scipy
    - shapely
    - cartopy
    - statsmodels
    - geopandas
    - mpltern
    - pyrolite
